version: '2'
services:
  kylin:
    build: .
    ports:
      - "7070:7070"
    hostname: quickstart.cloudera
    privileged: true
    tty: true
    volumes:
      - /data/hadoop-hdfs:/var/lib/hadoop-hdfs
      - /data/mysql:/var/lib/mysql
      
